### ISSUE TITLE
Unhandled exception if graylog goes down

### ISSUE THREAD

**Issue by trampster** [serilog-contrib/serilog-sinks-graylog#79]
If the graylog server goes down then 

Unhandled exception. System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s, ValueStopwatch stopwatch)
   at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Serilog.Sinks.Graylog.Core.SinkComponentsBuilder.GetIpAddress(String hostnameOrAddress)
   at Serilog.Sinks.Graylog.Core.SinkComponentsBuilder.MakeTransport()
   at Serilog.Sinks.Graylog.GraylogSink.<>c__DisplayClass3_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Serilog.Sinks.Graylog.GraylogSink.Dispose()
   at Serilog.Core.Sinks.RestrictedSink.Dispose()
   at Serilog.LoggerConfiguration.<>c__DisplayClass32_0.<CreateLogger>g__Dispose|0()
   at Serilog.Core.Logger.Dispose()
   at Program.<Main>$(String[] args) in /home/daniel/Work/DataApiTools/dataapi-soak/Program.cs:line 71
   at Program.<Main>(String[] args)

**Comment by whir1** [comment]
Okay and what?

**Comment by trampster** [comment]
Well I would rather not have to put try catches around every single logging statement in my code in order to handle a connection loss to my logging server.
