### ISSUE TITLE
Exception messages are not sent to Graylog with version 3.0.1

### ISSUE THREAD

**Issue by giuseppe-terrasi** [serilog-contrib/serilog-sinks-graylog#96]
When an exception is raised it is not sent to Graylog server using the package version 3.0.1. If I downgrade to version 2.3.0 it works fine.

Installed packages:
```
    <PackageReference Include="Serilog" Version="3.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="7.0.0" />
    <PackageReference Include="Serilog.Enrichers.ClientInfo" Version="1.2.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="2.2.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.Graylog" Version="3.0.1" />
    <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />

```
Serilog configuration:

```
  "Serilog": {
    "Using": [ "Serilog.Sinks.Console", "Serilog.Enrichers.Environment", "Serilog.Enrichers.Thread", "Serilog.Sinks.File", "Serilog.Enrichers.ClientInfo", "Serilog.Sinks.Graylog", "Serilog.Exceptions" ],
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "outputTemplate": "{Timestamp:o} [{Level:u3}] [{RequestId}, IP: {ClientIp} , Agent: {ClientAgent}] ({Application}/{MachineName}/{ThreadId}/{SourceContext}) {Indent:l}{Message:lj}{NewLine}{Exception}",
          "rollingInterval": "Day",
          "path": "/var/log/app.log"
        }
      },
      {
        "Name": "Graylog",
        "Args": {
          "hostnameOrAddress": "<myhost>",,
          "port": "12201",
          "transportType": "Udp"
        }
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId", "WithClientIp", "WithClientAgent" ],
    "Properties": {
      "Application": "MY-APP"
    }
  }	
```

**Comment by dmitriy-shleht** [comment]
I have the same problem, is there a solution?

**Comment by dmitriy-shleht** [comment]
@whir1 I suspect that the problem in the serializer after update from 2.3.0 to 3.0.0/3.0.1

**Installed packages:**
```
<PackageReference Include="Serilog" Version="3.0.1" />
<PackageReference Include="Serilog.Sinks.Graylog" Version="3.0.0" />
```

**Startup:**
```
static void Main(string[] args)
{
	Serilog.Debugging.SelfLog.Enable(msg => System.Diagnostics.Trace.WriteLine(msg));

	var log = new LoggerConfiguration()
		.MinimumLevel.Debug()
		.WriteTo.Graylog(new GraylogSinkOptions
		{
			HostnameOrAddress = "logger.fgr.net",
			Port = 12202,
			Facility = "svc",
			TransportType = Serilog.Sinks.Graylog.Core.Transport.TransportType.Udp
		})
		.CreateLogger();
        //It works
	//log.Information("Hello, world!");

	try
	{
		throw new Exception("test");
	}
	catch (Exception ex)
	{
                //Does not work
		log.Error(ex, ex.Message);
	}

	Console.ReadKey();
}
```

**Debug informations**
```
Oops something going wrong System.NotSupportedException: Serialization and deserialization of 'System.RuntimeType' instances are not supported. Path: $.
 ---> System.NotSupportedException: Serialization and deserialization of 'System.RuntimeType' instances are not supported.
   at System.Text.Json.Serialization.Converters.UnsupportedTypeConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteNode[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.SerializeToNode[TValue](TValue value, JsonSerializerOptions options)
   at Serilog.Sinks.Graylog.Core.MessageBuilders.GelfMessageBuilder.AddAdditionalField(JsonObject jObject, KeyValuePair`2 property, String memberPath)
   at Serilog.Sinks.Graylog.Core.MessageBuilders.GelfMessageBuilder.Build(LogEvent logEvent)
   at Serilog.Sinks.Graylog.Core.MessageBuilders.ExceptionMessageBuilder.Build(LogEvent logEvent)
   at Serilog.Sinks.Graylog.Core.GelfConverter.GetGelfJson(LogEvent logEvent)
   at Serilog.Sinks.Graylog.GraylogSink.EmitAsync(LogEvent logEvent)
   at Serilog.Sinks.Graylog.GraylogSink.Emit(LogEvent logEvent)
```

**Comment by tester349721** [comment]
in my opinion the problem is into this line 
serilog-sinks-graylog\src\Serilog.Sinks.Graylog.Core\MessageBuilders\ExceptionMessageBuilder.cs
...
public override JsonObject Build(LogEvent logEvent)
..
 `logEvent.AddOrUpdateProperty(new LogEventProperty("ExceptionType", new ScalarValue(logEvent.Exception.GetType())));`

as long as I change it to
`logEvent.AddOrUpdateProperty(new LogEventProperty("ExceptionType", new ScalarValue(logEvent.Exception.GetType().FullName)));`

It is working fine for me
